ALTER TYPE "QuoteDocumentType" ADD VALUE IF NOT EXISTS 'OFFICE_CLEANING_QUOTE';
ALTER TYPE "QuoteDocumentType" ADD VALUE IF NOT EXISTS 'DEEP_CLEANING_QUOTE';
ALTER TYPE "QuoteDocumentType" ADD VALUE IF NOT EXISTS 'END_OF_TENANCY_CLEANING_QUOTE';
ALTER TYPE "QuoteDocumentType" ADD VALUE IF NOT EXISTS 'AFTER_BUILDERS_CLEANING_QUOTE';
ALTER TYPE "QuoteDocumentType" ADD VALUE IF NOT EXISTS 'COMMERCIAL_CLEANING_QUOTE';
ALTER TYPE "QuoteDocumentType" ADD VALUE IF NOT EXISTS 'CARPET_CLEANING_QUOTE';
ALTER TYPE "QuoteDocumentType" ADD VALUE IF NOT EXISTS 'MOVE_IN_MOVE_OUT_CLEANING_QUOTE';
ALTER TYPE "QuoteDocumentType" ADD VALUE IF NOT EXISTS 'GENERAL_CLEANING_QUOTE';
